name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
        override: true

    - name: Format check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Run unit tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --lib --bins

    - name: Run doc tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --doc

  integration_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Setup test environment
      run: |
        docker-compose -f docker/docker-compose.test.yml up -d
        sleep 10 # Give services time to start
        
    - name: Run integration tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features test-integration -- --ignored

    - name: Tear down test environment
      if: always()
      run: docker-compose -f docker/docker-compose.test.yml down